### ISSUE TITLE
Raise Zombies causes segfault when raising human corpses.

### ISSUE THREAD

**Issue by Soviet5lo** [Soviet5lo/SlashTHEM#29]
Not exactly sure what is causing this but I'm assuming this is related to racial flags somehow. (this is the issue I meant to post earlier but instead posted a temp message, never use github when mostly asleep.)

Easy to reproduce: wish for human corpse in wizard mode and attempt to raise.  Immediate segfault.  Works fine for any other humanoid corpse, just not those marked MRACE_HUMAN.

**Comment by Soviet5lo** [comment]
And gdb output in wizard mode, using latest code

Program received signal SIGSEGV, Segmentation fault.
mon_nam (mtmp=0x0) at do_name.c:797
797     do_name.c: No such file or directory.
(gdb) bt
#0  mon_nam (mtmp=0x0) at do_name.c:797
#1  0x00005595b1afa9aa in techeffects (tech_no=1) at tech.c:1333
#2  0x00005595b1af739e in dotech () at tech.c:709
#3  0x00005595b18bbcca in doextcmd () at cmd.c:338
#4  0x00005595b18c8443 in rhack (cmd=0x5595b1bd5600 <in_line> "#")
    at cmd.c:3647
#5  0x00005595b1894c80 in moveloop () at allmain.c:654
#6  0x00005595b1b00e13 in main (argc=3, argv=0x7fff709948e8)
    at ../sys/unix/unixmain.c:309
(gdb)

**Comment by Soviet5lo** [comment]
Attempting to tame or create a human zombie or mummy via Summon Undead or Command Undead only results in them becoming _peaceful_, not tame.  Thinking its related to racial flags, but not sure where.
